name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        # MSRV and nightly
        version: [stable, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: Set toolchain
        run: |
          rustup override set ${{ matrix.version }}
          rustup update ${{ matrix.version }}

      - name: Rustfmt check
        run: |
          cargo test
